"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Bot, BriefcaseBusiness, CalendarClock, Check, ChevronRight, FileText, Filter, GitCompareArrows, History, LayoutDashboard, MessageSquareText, Plus, Search, ShieldCheck, Upload, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { FormField, StatusPill, WorkflowDialog, WorkspaceHeader } from "@/features/employee/workspace-frame";

type Candidate = { name: string; initials: string; role: string; experience: number; score: number; confidence: "Cao" | "Trung bình" | "Thấp"; reviewer: string; skills: string[]; evidence: string[]; gaps: string[]; breakdown: [number, number, number, number] };
type CvSection = "overview" | "requisitions" | "pipeline" | "candidates" | "compare" | "reviews" | "history" | "model";

const candidates: Candidate[] = [
  { name: "Nguyễn Văn An", initials: "NA", role: "Senior Backend Engineer", experience: 6, score: 91, confidence: "Cao", reviewer: "Lan Nguyễn", skills: ["Node.js", "PostgreSQL", "AWS", "TypeScript"], evidence: ["5 năm xây dựng API Node.js/TypeScript", "Thiết kế PostgreSQL cho hệ thống 2M users", "AWS Certified Solutions Architect"], gaps: ["Chưa tìm thấy bằng chứng Kubernetes", "Kafka chỉ được nhắc trong phần kỹ năng"], breakdown: [42, 27, 13, 9] },
  { name: "Trần Minh Khoa", initials: "TK", role: "Backend Engineer", experience: 5, score: 86, confidence: "Cao", reviewer: "Lan Nguyễn", skills: ["Java", "Kafka", "PostgreSQL"], evidence: ["Kafka production trong 3 dự án", "5 năm Java/Spring Boot", "PostgreSQL ở quy mô thương mại"], gaps: ["Kinh nghiệm Node.js chưa rõ"], breakdown: [39, 26, 13, 8] },
  { name: "Lê Hoàng Vy", initials: "LV", role: "Full-stack Engineer", experience: 4, score: 82, confidence: "Trung bình", reviewer: "Chưa gán", skills: ["TypeScript", "React", "Node.js"], evidence: ["TypeScript toàn thời gian từ 2022", "Node.js trong hai sản phẩm nội bộ"], gaps: ["Chưa có bằng chứng hệ thống quy mô lớn"], breakdown: [40, 23, 11, 8] },
  { name: "Phạm Gia Bảo", initials: "GB", role: "Software Engineer", experience: 3, score: 74, confidence: "Trung bình", reviewer: "Mai Anh", skills: ["Python", "FastAPI", "Docker"], evidence: ["REST API với FastAPI", "Docker CI/CD cơ bản"], gaps: ["Thiếu Node.js và PostgreSQL chuyên sâu"], breakdown: [32, 22, 12, 8] },
  { name: "Võ Thu Linh", initials: "TL", role: "Junior Backend Engineer", experience: 2, score: 68, confidence: "Thấp", reviewer: "Chưa gán", skills: ["Node.js", "MongoDB"], evidence: ["2 năm Node.js"], gaps: ["Thiếu kinh nghiệm senior", "Chưa có PostgreSQL/AWS"], breakdown: [31, 19, 10, 8] },
];
const dimensions = [["Kỹ năng", 45], ["Kinh nghiệm", 30], ["Chứng chỉ", 15], ["Ngoại ngữ", 10]] as const;
const nav: Array<{ id: CvSection; label: string; icon: typeof LayoutDashboard }> = [
  { id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "requisitions", label: "Requisitions", icon: BriefcaseBusiness }, { id: "pipeline", label: "Interview Pipeline", icon: CalendarClock }, { id: "candidates", label: "Candidate Queue", icon: UsersRound }, { id: "compare", label: "Compare", icon: GitCompareArrows }, { id: "reviews", label: "Review Decisions", icon: Check }, { id: "history", label: "History", icon: History }, { id: "model", label: "Model Notes", icon: Bot },
];

export function AiCvWorkspace() {
  const [section, setSection] = useState<CvSection>("overview");
  const [selectedName, setSelectedName] = useState(candidates[0].name);
  const [query, setQuery] = useState("");
  const [minScore, setMinScore] = useState(0);
  const [confidence, setConfidence] = useState("all");
  const [statuses, setStatuses] = useState<Record<string, string>>({});
  const [selectedForCompare, setSelectedForCompare] = useState<string[]>([candidates[0].name, candidates[1].name, candidates[2].name]);
  const [noteOpen, setNoteOpen] = useState(false);
  const [analysisOpen, setAnalysisOpen] = useState(false);
  const [note, setNote] = useState("");
  const [notes, setNotes] = useState<Record<string, string>>({});
  const selected = candidates.find((candidate) => candidate.name === selectedName) ?? candidates[0];
  const visible = useMemo(() => candidates.filter((candidate) => `${candidate.name} ${candidate.role} ${candidate.skills.join(" ")}`.toLowerCase().includes(query.toLowerCase()) && candidate.score >= minScore && (confidence === "all" || candidate.confidence === confidence)).sort((a, b) => b.score - a.score), [confidence, minScore, query]);
  const compareCandidates = candidates.filter((candidate) => selectedForCompare.includes(candidate.name)).slice(0, 3);

  function decide(status: string) { setStatuses((current) => ({ ...current, [selected.name]: status })); toast.success(`${selected.name}: ${status}. Quyết định HR đã được ghi lịch sử.`); }
  function saveNote() { if (note.trim().length < 8) { toast.error("Ghi chú cần ít nhất 8 ký tự."); return; } setNotes((current) => ({ ...current, [selected.name]: note.trim() })); setNote(""); setNoteOpen(false); toast.success("Đã lưu ghi chú của reviewer."); }
  function toggleCompare(name: string) { setSelectedForCompare((current) => current.includes(name) ? current.filter((item) => item !== name) : current.length < 3 ? [...current, name] : current); }

  return <div className="ai-product-shell ai-cv-product">
    <WorkspaceHeader title="AI CV Intelligence" subtitle="ATS Intelligence · REQ-2026-041 · JD v3" action={<div className="ai-product-actions"><StatusPill tone="success"><ShieldCheck size={14} strokeWidth={1.5} /> Human decision</StatusPill><button className="primary-button" onClick={() => setAnalysisOpen(true)}><Plus size={15} strokeWidth={1.5} /> Phân tích CV</button></div>} />
    <nav className="ai-internal-nav" aria-label="Điều hướng AI CV">{nav.map((item) => { const Icon = item.icon; return <button className={section === item.id ? "is-active" : ""} key={item.id} onClick={() => setSection(item.id)}><Icon size={15} strokeWidth={1.5} /><span>{item.label}</span></button>; })}</nav>

    {section === "overview" && <section className="ai-overview-compact"><div className="ai-activity-strip"><div><strong>REQ-2026-041</strong><span>Backend Engineer · đang tuyển</span></div><div><strong>5 / 14</strong><span>CV đã phân tích</span></div><div><strong>2</strong><span>Chờ human review</span></div></div><div className="ai-overview-actions"><button className="primary-button" onClick={() => setSection("candidates")}>Mở Candidate Queue <ChevronRight size={15} /></button><button className="secondary-button" onClick={() => setSection("compare")}>So sánh top candidates</button></div></section>}

    {section === "requisitions" && <section className="requisition-workspace"><aside><span className="eyebrow">ACTIVE REQUISITIONS</span>{[["REQ-2026-041","Backend Engineer","14 candidates"],["REQ-2026-039","Product Designer","8 candidates"],["REQ-2026-035","Data Analyst","Review complete"]].map((item, index) => <button className={index === 0 ? "is-active" : ""} key={item[0]}><BriefcaseBusiness size={16} strokeWidth={1.5} /><span><strong>{item[1]}</strong><small>{item[0]} · {item[2]}</small></span><ChevronRight size={14} /></button>)}</aside><article><header><div><span className="eyebrow">REQ-2026-041 · JD VERSION 3</span><h2>Senior Backend Engineer</h2><p>Công nghệ thông tin · Recruiter: Nguyễn Thanh Lan · tạo 28/09/2026</p></div><StatusPill tone="success">Đang tuyển</StatusPill></header><div className="requisition-tabs"><button className="is-active">Candidate Queue</button><button onClick={() => toast.info("Đã mở Scoring Criteria.")}>Scoring Criteria</button><button onClick={() => toast.info("Đã mở Review Progress.")}>Review Progress</button><button onClick={() => setSection("history")}>Analysis History</button></div><div className="criteria-grid">{dimensions.map(([label, weight]) => <div key={label}><span>{label}</span><strong>{weight}%</strong><i><b style={{ width: `${weight * 2}%` }} /></i></div>)}</div><div className="requisition-note"><MessageSquareText size={17} /><p><strong>Analysis policy:</strong> must-have Node.js + SQL; protected attributes excluded; score never auto-rejects a candidate.</p></div></article></section>}

    {(section === "candidates" || section === "reviews") && <section className="candidate-operations"><div className="candidate-toolbar"><div className="compact-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm ứng viên, kỹ năng..." /></div><div className="candidate-filters"><Filter size={14} /><select aria-label="Điểm tối thiểu" value={minScore} onChange={(event) => setMinScore(Number(event.target.value))}><option value={0}>Mọi điểm số</option><option value={80}>80 điểm trở lên</option><option value={90}>90 điểm trở lên</option></select><select aria-label="Độ tin cậy" value={confidence} onChange={(event) => setConfidence(event.target.value)}><option value="all">Mọi confidence</option><option>Cao</option><option>Trung bình</option><option>Thấp</option></select></div></div><div className="candidate-workbench"><aside className="candidate-queue"><div className="queue-column-head"><span>{visible.length} candidates</span><button onClick={() => setSection("compare")}>Compare ({selectedForCompare.length})</button></div>{visible.map((candidate) => <button className={selected.name === candidate.name ? "is-active" : ""} key={candidate.name} onClick={() => setSelectedName(candidate.name)}><input type="checkbox" checked={selectedForCompare.includes(candidate.name)} onChange={() => toggleCompare(candidate.name)} onClick={(event) => event.stopPropagation()} aria-label={`Chọn ${candidate.name} để so sánh`} /><span className="avatar avatar-sm">{candidate.initials}</span><span><strong>{candidate.name}</strong><small>{candidate.role} · {candidate.experience} năm</small><em>{candidate.skills.slice(0,3).join(" · ")}</em></span><b className={candidate.score >= 85 ? "high" : candidate.score >= 75 ? "medium" : "low"}>{candidate.score}</b></button>)}</aside><CandidateDossier candidate={selected} status={statuses[selected.name]} note={notes[selected.name]} onDecision={decide} onAddNote={() => setNoteOpen(true)} onCompare={() => { toggleCompare(selected.name); setSection("compare"); }} /></div></section>}

    {section === "compare" && <section className="comparison-workspace"><header><div><span className="eyebrow">ALIGNED COMPARISON</span><h2>Candidate comparison</h2><p>Chọn tối đa 3 ứng viên. Human reviewer quyết định độc lập với AI score.</p></div><button className="secondary-button" onClick={() => setSection("candidates")}>Thay đổi lựa chọn</button></header><div className="comparison-grid"><div className="compare-labels"><strong>Tiêu chí</strong>{["Overall score","Kinh nghiệm","Must-have","Nice-to-have","Confidence","Unresolved gaps","Reviewer note"].map((item) => <span key={item}>{item}</span>)}</div>{compareCandidates.map((candidate) => <article key={candidate.name}><header><span className="avatar">{candidate.initials}</span><div><strong>{candidate.name}</strong><small>{candidate.role}</small></div></header><b className="compare-score">{candidate.score}</b><span>{candidate.experience} năm</span><span>{candidate.skills.slice(0,2).join(", ")}</span><span>{candidate.skills.slice(2).join(", ") || "—"}</span><span><StatusPill tone={candidate.confidence === "Cao" ? "success" : candidate.confidence === "Thấp" ? "warning" : "blue"}>{candidate.confidence}</StatusPill></span><span>{candidate.gaps.length} mục</span><span>{notes[candidate.name] ?? "Chưa có ghi chú"}</span></article>)}</div></section>}

    {section === "history" && <section className="ai-history-workspace"><header><span className="eyebrow">TRACE VIEW</span><h2>Analysis & decision history</h2></header>{[["09:36","AI analyzed","CV-Match 4.2 đối chiếu JD v3","System"],["09:42","HR opened review","Nguyễn Văn An · score 91","Nguyễn Thanh Lan"],["10:05","Reviewer note","Cần xác minh Kubernetes production","Nguyễn Thanh Lan"],["10:22","Compared","Nguyễn Văn An với Trần Minh Khoa","Nguyễn Thanh Lan"],["10:31","Decision updated","Nguyễn Văn An → Shortlisted","Nguyễn Thanh Lan"]].map((event) => <div key={event[0]}><time>{event[0]}</time><i /><span><strong>{event[1]}</strong><p>{event[2]}</p></span><small>{event[3]}</small></div>)}</section>}

    {section === "model" && <section className="model-notes-workspace"><div><Bot size={22} /><span><strong>CV-Match 4.2</strong><small>Explainable ranking · production</small></span><StatusPill tone="success">Healthy</StatusPill></div><h2>How this result was produced</h2><p>Điểm số là tổng có trọng số từ yêu cầu JD, bằng chứng kinh nghiệm và chứng chỉ được trích dẫn. Model không sử dụng tuổi, giới tính, ảnh, tình trạng hôn nhân hoặc thuộc tính được bảo vệ.</p><div className="model-rule-list"><p><strong>Evidence first</strong><span>Mọi tiêu chí cần liên kết tới đoạn CV hoặc được đánh dấu chưa xác minh.</span></p><p><strong>Confidence separate from score</strong><span>Điểm phù hợp cao vẫn có thể có confidence thấp khi bằng chứng mơ hồ.</span></p><p><strong>No autonomous rejection</strong><span>AI không tự động loại ứng viên; quyết định luôn thuộc về reviewer.</span></p></div></section>}

    <WorkflowDialog open={analysisOpen} onOpenChange={setAnalysisOpen} title="Phân tích CV mới" description="REQ-2026-041 · JD v3 · yêu cầu human review" footer={<><button className="secondary-button" onClick={() => setAnalysisOpen(false)}>Hủy</button><button className="primary-button" onClick={() => { setAnalysisOpen(false); setSection("candidates"); toast.success("CV đã được phân tích và thêm vào Candidate Queue."); }}>Bắt đầu phân tích</button></>}><FormField label="Tệp CV" required><label className="upload-zone"><Upload size={18} /><span>Chọn PDF hoặc DOCX</span><input className="sr-only" type="file" accept=".pdf,.doc,.docx" /></label></FormField><div className="ai-caution"><ShieldCheck size={16} /><p>Tệp chỉ được phân tích khi recruiter chủ động gửi vào AI CV Intelligence.</p></div></WorkflowDialog>
    <WorkflowDialog open={noteOpen} onOpenChange={setNoteOpen} title="Reviewer note" description={selected.name} footer={<><button className="secondary-button" onClick={() => setNoteOpen(false)}>Hủy</button><button className="primary-button" onClick={saveNote}>Lưu ghi chú</button></>}><FormField label="Nội dung" required><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Điểm cần xác minh trong vòng phỏng vấn..." /></FormField></WorkflowDialog>
    {section === "pipeline" && <section className="recruitment-pipeline"><div className="pipeline-copy"><span className="eyebrow">INTERVIEW OPERATIONS</span><h2>Lịch phỏng vấn và screening</h2><p>Chuyển kết quả AI thành quy trình tuyển dụng có người phụ trách, lịch hẹn và bằng chứng phỏng vấn rõ ràng.</p><div className="pipeline-stages">{[["Screening","5",true],["Technical interview","3",true],["Culture interview","2",false],["Offer","1",false]].map(([label,count,active]) => <div className={active ? "is-active" : ""} key={String(label)}><strong>{count}</strong><span>{label}</span></div>)}</div><div className="pipeline-interviews"><span className="eyebrow">UPCOMING INTERVIEWS</span>{[["09:30","Nguyễn Văn An","Technical · Nguyễn Đức Long"],["14:00","Trần Minh Khoa","System design · Phạm Hoàng"],["16:30","Lê Hoàng Vy","Recruiter follow-up · Nguyễn Thanh Lan"]].map((item) => <button key={item[0]} onClick={() => toast.info(`Đã mở lịch phỏng vấn ${item[1]}.`)}><time>{item[0]}</time><span><strong>{item[1]}</strong><small>{item[2]}</small></span><ChevronRight size={15} /></button>)}</div></div></section>}
  </div>;
}

function CandidateDossier({ candidate, status, note, onDecision, onAddNote, onCompare }: { candidate: Candidate; status?: string; note?: string; onDecision: (status: string) => void; onAddNote: () => void; onCompare: () => void }) {
  return <article className="candidate-dossier"><header><div className="candidate-title"><span className="avatar">{candidate.initials}</span><div><span>CANDIDATE DOSSIER</span><h2>{candidate.name}</h2><p>{candidate.role} · {candidate.experience} năm</p></div></div><div className="dossier-score"><span>AI MATCH</span><strong>{candidate.score}</strong><small>Confidence · {candidate.confidence}</small></div></header><div className="dossier-tools"><button onClick={onCompare}><GitCompareArrows size={14} /> Compare</button><button onClick={onAddNote}><MessageSquareText size={14} /> Add note</button><button onClick={() => toast.success("Đã mở CV gốc và ghi audit lượt xem.")}><FileText size={14} /> Original CV</button><StatusPill tone={status === "Shortlisted" ? "success" : status === "Needs Review" ? "warning" : "neutral"}>{status ?? "Chưa đánh giá"}</StatusPill></div><div className="dossier-analysis"><section><span className="eyebrow">REQUIREMENT COVERAGE</span>{dimensions.map(([label, max], index) => <div className="requirement-row" key={label}><p><span>{label}</span><strong>{candidate.breakdown[index]} / {max}</strong></p><i><b style={{ width: `${candidate.breakdown[index] / max * 100}%` }} /></i></div>)}</section><section><span className="eyebrow">SOURCE-LINKED EVIDENCE</span>{candidate.evidence.map((item, index) => <div className="evidence-source" key={item}><span>{String(index + 1).padStart(2,"0")}</span><p>{item}</p><button onClick={() => toast.info(`Đã mở nguồn CV #${index + 1}.`)}>Source</button></div>)}</section></div><div className="dossier-gaps"><AlertTriangle size={17} /><div><strong>Gaps requiring verification</strong>{candidate.gaps.map((gap) => <p key={gap}>{gap}</p>)}</div></div>{note && <div className="reviewer-note"><MessageSquareText size={16} /><div><strong>Reviewer note</strong><p>{note}</p></div></div>}<footer><p><ShieldCheck size={15} /> AI advisory only · HR owns the final decision.</p><div><button className="secondary-button" onClick={() => onDecision("Needs Review")}>Needs Review</button><button className="primary-button" onClick={() => onDecision("Shortlisted")}><Check size={15} /> Shortlist</button></div></footer></article>;
}
