import { buildEffectiveSession } from "./engine";
import type { PermissionGrant, PersonaDefinition, PersonaId } from "./types";

const grant = (
  resource: string,
  actions: PermissionGrant["actions"],
  scope: PermissionGrant["scope"],
  source: PermissionGrant["source"],
  expiresAt?: string,
): PermissionGrant => ({ resource, actions, scope, source, expiresAt });

const baseEmployee: PermissionGrant[] = [
  grant("home", ["view"], "self", "base"),
  grant("profile", ["view", "edit"], "self", "base"),
  grant("attendance", ["view", "create"], "self", "base"),
  grant("approvals", ["view", "create"], "self", "base"),
  grant("daily-report", ["view", "create", "edit"], "self", "base"),
  grant("leave", ["view", "create", "edit"], "self", "base"),
  grant("expenses", ["view", "create", "edit"], "self", "base"),
  grant("email", ["view", "create", "edit"], "self", "base"),
  grant("payslip", ["view"], "self", "base"),
  grant("contracts", ["view"], "self", "base"),
  grant("offboarding-status", ["view"], "self", "base"),
  grant("notifications", ["view"], "self", "base"),
  grant("performance", ["view"], "self", "base"),
];

const commonFields = [
  { field: "phone", visibility: "visible" as const },
  { field: "address", visibility: "masked" as const },
  { field: "bankAccount", visibility: "masked" as const },
  { field: "salary", visibility: "hidden" as const },
  { field: "citizenId", visibility: "masked" as const },
];

const definitions: PersonaDefinition[] = [
  {
    id: "employee",
    label: "Nhân viên",
    shortLabel: "NV",
    role: "Product Designer",
    description: "Dịch vụ cá nhân · phạm vi bản thân",
    branch: "HCM-Q1",
    department: "Sản phẩm",
    grants: [...baseEmployee, grant("ai-wfh", ["view"], "self", "base")],
    scopeConstraints: ["self"],
    sensitiveFields: commonFields,
  },
  {
    id: "team-lead",
    label: "Nhân viên + Team Lead",
    shortLabel: "TL",
    role: "Team Lead · Data Platform",
    description: "Quyền bổ sung từ quan hệ nhóm",
    branch: "HCM-Q1",
    department: "Công nghệ thông tin",
    grants: [
      ...baseEmployee,
      grant("team", ["view"], "team", "relationship"),
      grant("approvals", ["view", "approve"], "team", "relationship"),
      grant("team-calendar", ["view"], "team", "relationship"),
      grant("ai-wfh", ["view", "edit"], "team", "relationship"),
      grant("expenses.review", ["view", "approve"], "team", "delegation", "2026-10-16"),
    ],
    scopeConstraints: ["team", "branch"],
    sensitiveFields: commonFields,
  },
  {
    id: "hr-total",
    label: "HR Tổng",
    shortLabel: "HR",
    role: "HR Operations Lead",
    description: "Mẫu quyền HR Tổng · toàn công ty",
    branch: "Toàn công ty",
    department: "Nhân sự",
    grants: [
      ...baseEmployee,
      grant("ai-wfh", ["view"], "self", "base"),
      grant("employees", ["view", "create", "edit", "export"], "company", "template"),
      grant("onboarding", ["view", "create", "edit"], "company", "template"),
      grant("hr-contracts", ["view", "create", "edit", "approve"], "company", "template"),
      grant("organization", ["view", "edit"], "company", "template"),
      grant("offboarding", ["view", "create", "edit", "approve"], "company", "template"),
      grant("attendance-monitoring", ["view", "edit", "approve", "export"], "company", "template"),
      grant("timesheets", ["view", "edit", "approve", "export"], "company", "template"),
      grant("expense-review", ["view", "approve", "export"], "company", "template"),
      grant("reports", ["view", "export"], "company", "template"),
      grant("misa-sync", ["view", "configure"], "company", "override"),
    ],
    scopeConstraints: ["company", "company"],
    sensitiveFields: [
      { field: "phone", visibility: "visible" },
      { field: "address", visibility: "visible" },
      { field: "bankAccount", visibility: "visible" },
      { field: "salary", visibility: "visible" },
      { field: "citizenId", visibility: "visible" },
    ],
  },
  {
    id: "hr-branch",
    label: "HR Chi nhánh",
    shortLabel: "CN",
    role: "HR Generalist · HCM-Q1",
    description: "Mẫu quyền HR Chi nhánh · HCM-Q1",
    branch: "HCM-Q1",
    department: "Nhân sự",
    grants: [
      ...baseEmployee,
      grant("ai-wfh", ["view"], "self", "base"),
      grant("employees", ["view", "create", "edit"], "branch", "template"),
      grant("onboarding", ["view", "create", "edit"], "branch", "template"),
      grant("hr-contracts", ["view", "create", "edit"], "branch", "template"),
      grant("offboarding", ["view", "create", "edit"], "branch", "template"),
      grant("attendance-monitoring", ["view", "edit"], "branch", "template"),
      grant("timesheets", ["view", "edit"], "branch", "template"),
      grant("expense-review", ["view", "approve"], "branch", "template"),
      grant("reports", ["view"], "branch", "template"),
    ],
    scopeConstraints: ["branch", "branch"],
    sensitiveFields: [
      { field: "phone", visibility: "visible" },
      { field: "address", visibility: "masked" },
      { field: "bankAccount", visibility: "masked" },
      { field: "salary", visibility: "hidden" },
      { field: "citizenId", visibility: "masked" },
    ],
  },
  {
    id: "recruiter",
    label: "HR Tuyển dụng",
    shortLabel: "TD",
    role: "Talent Acquisition Specialist",
    description: "Tuyển dụng + AI CV Intelligence",
    branch: "Toàn công ty",
    department: "Nhân sự",
    grants: [
      ...baseEmployee,
      grant("ai-wfh", ["view"], "self", "base"),
      grant("employees", ["view"], "company", "template"),
      grant("onboarding", ["view", "create"], "company", "template"),
      grant("ai-cv", ["view", "create", "edit"], "company", "template"),
    ],
    scopeConstraints: ["company", "company"],
    sensitiveFields: commonFields,
  },
  {
    id: "compensation",
    label: "HR C&B",
    shortLabel: "C&B",
    role: "Compensation & Benefits",
    description: "Chấm công · phúc lợi · MISA",
    branch: "Toàn công ty",
    department: "Nhân sự",
    grants: [
      ...baseEmployee,
      grant("ai-wfh", ["view"], "self", "base"),
      grant("employees", ["view"], "company", "template"),
      grant("timesheets", ["view", "edit", "approve", "export"], "company", "template"),
      grant("attendance-monitoring", ["view", "edit", "approve", "export"], "company", "template"),
      grant("expense-review", ["view", "approve", "export"], "company", "template"),
      grant("reports", ["view", "export"], "company", "template"),
      grant("misa-sync", ["view", "configure"], "company", "template"),
    ],
    restrictions: [{ resource: "profile", actions: ["edit"] }],
    scopeConstraints: ["company", "company"],
    sensitiveFields: [
      { field: "phone", visibility: "visible" },
      { field: "address", visibility: "masked" },
      { field: "bankAccount", visibility: "visible" },
      { field: "salary", visibility: "visible" },
      { field: "citizenId", visibility: "masked" },
    ],
  },
  {
    id: "system-admin",
    label: "System Admin",
    shortLabel: "SA",
    role: "System Administrator",
    description: "Cấu hình hệ thống · không vận hành HR",
    branch: "Toàn công ty",
    department: "Công nghệ thông tin",
    grants: [
      ...baseEmployee,
      grant("ai-wfh", ["view"], "self", "base"),
      grant("admin-overview", ["view"], "company", "template"),
      grant("branches-gps", ["view", "create", "edit", "configure"], "company", "template"),
      grant("accounts", ["view", "create", "edit", "assign", "export"], "company", "template"),
      grant("permissions", ["view", "edit", "configure", "audit"], "company", "template"),
      grant("access-reviews", ["view", "approve", "audit"], "company", "template"),
      grant("delegation", ["view", "create", "edit", "configure", "audit"], "company", "template"),
      grant("catalogs", ["view", "create", "edit", "configure"], "company", "template"),
      grant("email-dlp", ["view", "configure", "audit"], "company", "template"),
      grant("notification-config", ["view", "configure", "audit"], "company", "template"),
      grant("integrations", ["view", "configure", "audit"], "company", "template"),
      grant("audit", ["view", "audit", "export"], "company", "template"),
      grant("ai-governance", ["view", "configure", "audit"], "company", "template"),
    ],
    scopeConstraints: ["company", "company"],
    sensitiveFields: [
      { field: "phone", visibility: "masked" },
      { field: "address", visibility: "hidden" },
      { field: "bankAccount", visibility: "hidden" },
      { field: "salary", visibility: "hidden" },
      { field: "citizenId", visibility: "hidden" },
    ],
  },
];

export const personas = definitions.map(buildEffectiveSession);

export function getPersona(id: PersonaId) {
  return personas.find((persona) => persona.id === id) ?? personas[0];
}
