"use client";
/* eslint-disable react/no-unescaped-entities */

import Image from "next/image";
import { useMemo, useState } from "react";
import { AlertTriangle, Check, Clock3, Eye, FileCheck2, Filter, History, LayoutDashboard, LockKeyhole, MessageSquareText, Monitor, Search, ShieldCheck, Trash2, UserCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { FormField, StatusPill, WorkflowDialog } from "@/features/employee/workspace-frame";
import { useSession } from "@/features/session/session-context";

type Evidence = { time: string; app: string; detail: string; confidence: number; tone: "high" | "low"; task: string };
type WfhCase = { initials: string; name: string; team: string; score: number; coverage: number; report: string[]; missing: string; evidence: Evidence[]; consent: string; reviewer: string; priority: "Cao" | "Trung bình"; status: "Chờ review" | "Đang review" | "Đã xử lý" };
type WfhSection = "overview" | "queue" | "employees" | "case" | "history" | "privacy";

const baseEvidence: Evidence[] = [
  { time: "09:12", app: "VS Code", detail: "API pagination implementation", confidence: 96, tone: "high", task: "API pagination" },
  { time: "10:34", app: "Jira", detail: "DP-381 review", confidence: 98, tone: "high", task: "PR review" },
  { time: "11:16", app: "GitHub", detail: "PR #184", confidence: 97, tone: "high", task: "PR review" },
  { time: "14:07", app: "Video content", detail: "Có thể là tài liệu học tập", confidence: 61, tone: "low", task: "API documentation" },
  { time: "15:22", app: "DBeaver", detail: "ETL mapping", confidence: 94, tone: "high", task: "ETL validation" },
  { time: "16:41", app: "Slack", detail: "#data-platform", confidence: 91, tone: "high", task: "Team communication" },
];
const seedCases: WfhCase[] = [
  { initials: "BT", name: "Bùi Thanh Tâm", team: "Data Platform", score: 89, coverage: 83, report: ["API pagination", "DB mapping", "PR review", "Team communication", "ETL validation"], missing: "API documentation", evidence: baseEvidence, consent: "Đã đồng ý · 01/10/2026", reviewer: "Trần Minh Quân", priority: "Cao", status: "Chờ review" },
  { initials: "TK", name: "Trần Minh Khoa", team: "Data Platform", score: 94, coverage: 100, report: ["Kafka consumer", "PR review", "Unit tests", "Team communication"], missing: "Không có", evidence: baseEvidence.map((item) => ({ ...item, confidence: Math.min(99, item.confidence + 4), tone: "high" as const })), consent: "Đã đồng ý · 01/10/2026", reviewer: "Trần Minh Quân", priority: "Trung bình", status: "Đang review" },
  { initials: "LV", name: "Lê Hoàng Vy", team: "Data Platform", score: 91, coverage: 80, report: ["Dashboard query", "DB mapping", "Review metrics", "Team communication"], missing: "Data dictionary", evidence: baseEvidence.slice(0,5), consent: "Đã đồng ý · 02/10/2026", reviewer: "Chưa gán", priority: "Trung bình", status: "Chờ review" },
];
const nav: Array<{ id: WfhSection; label: string; icon: typeof LayoutDashboard }> = [
  { id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "queue", label: "Review Queue", icon: FileCheck2 }, { id: "employees", label: "Employees", icon: UsersRound }, { id: "case", label: "Case Review", icon: Search }, { id: "history", label: "Decision Log", icon: History }, { id: "privacy", label: "Privacy & Access", icon: LockKeyhole },
];

export function WfhAiWorkspace() {
  const { can } = useSession();
  return can("ai-wfh", "edit") ? <WfhReviewerWorkspace /> : <EmployeeWfhIntelligence />;
}

function WfhReviewerWorkspace() {
  const [section, setSection] = useState<WfhSection>("overview");
  const [cases, setCases] = useState(seedCases);
  const [selectedName, setSelectedName] = useState(seedCases[0].name);
  const [query, setQuery] = useState("");
  const [confidence, setConfidence] = useState("all");
  const [status, setStatus] = useState("all");
  const [contextOpen, setContextOpen] = useState(false);
  const [context, setContext] = useState("");
  const [preview, setPreview] = useState<Evidence | null>(null);
  const [validEvents, setValidEvents] = useState<string[]>([]);
  const [deletedEvents, setDeletedEvents] = useState<string[]>([]);
  const [decisions, setDecisions] = useState<Array<{ time: string; action: string; detail: string; actor: string }>>([{ time: "09:14", action: "AI classification completed", detail: "6 evidence events · 1 low-confidence", actor: "WFH-Signal 3.1" }]);
  const selected = cases.find((item) => item.name === selectedName) ?? cases[0];
  const visibleCases = useMemo(() => cases.filter((item) => `${item.name} ${item.team}`.toLowerCase().includes(query.toLowerCase()) && (confidence === "all" || (confidence === "low" ? item.evidence.some((event) => event.tone === "low") : !item.evidence.some((event) => event.tone === "low"))) && (status === "all" || item.status === status)), [cases, confidence, query, status]);
  const visibleEvidence = selected.evidence.filter((item) => !deletedEvents.includes(`${selected.name}-${item.time}`));

  function openCase(name: string) { setSelectedName(name); setSection("case"); }
  function assignReviewer(name: string, reviewer: string) { setCases((current) => current.map((item) => item.name === name ? { ...item, reviewer, status: "Đang review" } : item)); toast.success(`Đã gán ${reviewer} review ${name}.`); }
  function record(action: string, detail: string) { setDecisions((current) => [{ time: "Vừa xong", action, detail, actor: "Trần Minh Quân · Team Lead" }, ...current]); }
  function saveContext() { if (context.trim().length < 10) { toast.error("Cần ít nhất 10 ký tự ngữ cảnh."); return; } record("Reviewer added context", `${selected.name}: ${context.trim()}`); setContext(""); setContextOpen(false); toast.success("Đã lưu ngữ cảnh và audit."); }
  function resolveCase(outcome: string) { setCases((current) => current.map((item) => item.name === selected.name ? { ...item, status: outcome === "Đã xử lý" ? "Đã xử lý" : "Đang review" } : item)); record(outcome === "Đã xử lý" ? "Case resolved" : "Employee clarification requested", selected.name); toast.success(outcome === "Đã xử lý" ? "Case đã được xử lý bởi con người." : "Đã gửi yêu cầu làm rõ."); }

  return <div className="ai-product-shell wfh-product">
    <header className="ai-product-header"><div className="ai-product-identity"><span className="ai-product-symbol"><ShieldCheck size={20} /></span><div><span>OHRIISE SPECIALIST APPLICATION</span><h1>WFH Intelligence</h1><p>Human Review & Evidence Analysis · 07/10/2026</p></div></div><div className="ai-product-actions"><StatusPill tone="warning"><UserCheck size={14} /> Human review required</StatusPill><button className="primary-button" onClick={() => setSection("queue")}>Mở Review Queue</button></div></header>
    <nav className="ai-internal-nav" aria-label="Điều hướng WFH Intelligence">{nav.map((item) => { const Icon = item.icon; return <button className={section === item.id ? "is-active" : ""} key={item.id} onClick={() => setSection(item.id)}><Icon size={15} /><span>{item.label}</span></button>; })}</nav>

    {section === "overview" && <section className="ai-app-overview"><div className="ai-overview-copy"><span className="eyebrow">TODAY'S HUMAN REVIEW</span><h2>Tập trung vào sự kiện cần ngữ cảnh, không phán xét tự động.</h2><p>3 phiên WFH đang hoạt động, 1 sự kiện confidence thấp và 2 case đang chờ reviewer.</p><div className="ai-overview-actions"><button className="primary-button" onClick={() => setSection("queue")}>Review low-confidence case</button><button className="secondary-button" onClick={() => openCase(seedCases[0].name)}>Mở employee session</button></div><div className="ai-activity-strip"><div><strong>3</strong><span>Active sessions</span></div><div><strong>92%</strong><span>Evidence coverage</span></div><div><strong>1</strong><span>Needs context</span></div></div></div><div className="ai-landing-art"><Image src="/assets/ohriise/06_wfh-monitoring_ai-activity-review_remote-work.png" alt="Minh họa WFH Intelligence oHRiise" width={430} height={323} priority /></div></section>}

    {section === "queue" && <section className="wfh-queue-workspace"><div className="candidate-toolbar"><div className="compact-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm nhân viên, team..." /></div><div className="candidate-filters"><Filter size={14} /><select value={confidence} onChange={(event) => setConfidence(event.target.value)} aria-label="Lọc confidence"><option value="all">Mọi confidence</option><option value="low">Có low-confidence</option><option value="high">Không có cảnh báo</option></select><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Lọc trạng thái"><option value="all">Mọi trạng thái</option><option>Chờ review</option><option>Đang review</option><option>Đã xử lý</option></select></div></div><div className="wfh-case-list"><div className="wfh-case-head"><span>Employee / team</span><span>Coverage</span><span>Confidence</span><span>Report alignment</span><span>Reviewer</span><span>Status</span><span></span></div>{visibleCases.map((item) => <div key={item.name}><div className="table-person"><span className="avatar avatar-sm">{item.initials}</span><span><strong>{item.name}</strong><small>{item.team} · WFH cả ngày</small></span></div><strong>{item.coverage}%</strong><StatusPill tone={item.evidence.some((event) => event.tone === "low") ? "warning" : "success"}>{item.evidence.some((event) => event.tone === "low") ? "Review" : "High"}</StatusPill><span>{item.report.length}/{item.report.length + (item.missing === "Không có" ? 0 : 1)} tasks</span><select aria-label={`Gán reviewer cho ${item.name}`} value={item.reviewer} onChange={(event) => assignReviewer(item.name, event.target.value)}><option>Chưa gán</option><option>Trần Minh Quân</option><option>Nguyễn Thanh Lan</option></select><StatusPill tone={item.status === "Đã xử lý" ? "success" : item.status === "Đang review" ? "blue" : "warning"}>{item.status}</StatusPill><button onClick={() => openCase(item.name)}>Review <Eye size={14} /></button></div>)}</div></section>}

    {section === "employees" && <section className="wfh-employee-directory"><header><div><span className="eyebrow">WFH EMPLOYEES</span><h2>Sessions hôm nay</h2></div><span>3 active · Data Platform</span></header>{cases.map((item) => <button key={item.name} onClick={() => openCase(item.name)}><span className="avatar">{item.initials}</span><span><strong>{item.name}</strong><small>{item.team} · consent active</small></span><span><strong>{item.score}%</strong><small>work signal</small></span><span><strong>{item.coverage}%</strong><small>coverage</small></span><StatusPill tone={item.status === "Đã xử lý" ? "success" : "warning"}>{item.status}</StatusPill><Eye size={16} /></button>)}</section>}

    {section === "case" && <section className="wfh-case-workbench"><aside className="case-session-list"><span className="eyebrow">TODAY'S SESSIONS</span>{cases.map((item) => <button className={item.name === selected.name ? "is-active" : ""} key={item.name} onClick={() => setSelectedName(item.name)}><span className="avatar avatar-sm">{item.initials}</span><span><strong>{item.name}</strong><small>{item.status} · {item.coverage}%</small></span>{item.evidence.some((event) => event.tone === "low") && <i />}</button>)}</aside><article className="case-evidence-pane"><header><div><span className="eyebrow">CASE REVIEW · {selected.team}</span><h2>{selected.name}</h2><p>WFH cả ngày · {visibleEvidence.length} evidence events · consent active</p></div><div><strong>{selected.score}%</strong><span>Work-related signal</span></div></header><div className="evidence-stream">{visibleEvidence.map((item) => { const key = `${selected.name}-${item.time}`; const valid = validEvents.includes(key); return <div className={item.tone === "low" && !valid ? "needs-review" : ""} key={item.time}><time>{item.time}</time><span className="evidence-node"><Monitor size={14} /></span><div><p><strong>{item.app}</strong><StatusPill tone={valid ? "success" : item.tone === "low" ? "warning" : "blue"}>{valid ? "Valid" : `${item.confidence}%`}</StatusPill></p><span>{item.detail}</span><small>Linked task · {item.task}</small>{item.tone === "low" && !valid && <em>Possible learning material · needs human context</em>}</div><button onClick={() => setPreview(item)}><Eye size={15} /></button></div>})}</div></article><aside className="case-inspector"><div><span className="eyebrow">REPORT ALIGNMENT</span><strong className="alignment-value">{selected.report.length}/{selected.report.length + (selected.missing === "Không có" ? 0 : 1)}</strong><p>Daily Report tasks có evidence liên quan</p></div><div className="alignment-list">{selected.report.slice(0,4).map((item) => <div key={item}><Check size={13} /><span>{item}</span></div>)}{selected.missing !== "Không có" && <div className="missing"><Clock3 size={13} /><span>{selected.missing}</span></div>}</div><div className="human-action-stack"><button className="secondary-button" onClick={() => setContextOpen(true)}><MessageSquareText size={14} /> Add context</button><button className="secondary-button" onClick={() => resolveCase("Đang review")}>Request clarification</button><button className="primary-button" onClick={() => resolveCase("Đã xử lý")}><Check size={14} /> Resolve · no issue</button></div><div className="privacy-mini"><LockKeyhole size={14} /><span>Blur active · retention 30 days · access audited</span></div></aside></section>}

    {section === "history" && <section className="ai-history-workspace"><header><span className="eyebrow">HUMAN DECISION LOG</span><h2>Review history</h2></header>{decisions.map((event, index) => <div key={`${event.time}-${index}`}><time>{event.time}</time><i /><span><strong>{event.action}</strong><p>{event.detail}</p></span><small>{event.actor}</small></div>)}</section>}

    {section === "privacy" && <section className="privacy-command-center"><header><ShieldCheck size={24} /><div><span className="eyebrow">PRIVACY & ACCESS</span><h2>Evidence protection</h2><p>Ai có thể truy cập, lý do và vòng đời dữ liệu.</p></div></header><div className="privacy-policy-grid"><div><UserCheck size={18} /><span><strong>Consent</strong><small>{selected.consent}</small></span><StatusPill tone="success">Active</StatusPill></div><div><LockKeyhole size={18} /><span><strong>Sensitive-content blur</strong><small>Áp dụng trước khi lưu</small></span><StatusPill tone="success">Enabled</StatusPill></div><div><Clock3 size={18} /><span><strong>Retention</strong><small>Tự động xóa evidence</small></span><b>30 ngày</b></div><div><Eye size={18} /><span><strong>Last accessed</strong><small>Daily Report alignment</small></span><b>10:42 · Team Lead</b></div></div><div className="privacy-access-log"><span className="eyebrow">ACCESS LOG</span>{[["10:42","Trần Minh Quân","Review low-confidence evidence","Allowed"],["09:58","Nguyễn Thanh Lan","Compliance spot check","Allowed"],["09:14","System","Classification pipeline","Processed"]].map((row) => <div key={row[0]}><time>{row[0]}</time><strong>{row[1]}</strong><span>{row[2]}</span><StatusPill tone="success">{row[3]}</StatusPill></div>)}</div></section>}

    <WorkflowDialog open={contextOpen} onOpenChange={setContextOpen} title="Add reviewer context" description={`${selected.name} · human review`} footer={<><button className="secondary-button" onClick={() => setContextOpen(false)}>Hủy</button><button className="primary-button" onClick={saveContext}>Lưu & ghi audit</button></>}><div className="ai-caution"><AlertTriangle size={17} /><p>Low-confidence không đồng nghĩa với vi phạm. Hãy mô tả ngữ cảnh công việc quan sát được.</p></div><FormField label="Ngữ cảnh của reviewer" required><textarea value={context} onChange={(event) => setContext(event.target.value)} placeholder="Video là khóa học Kafka dùng cho DP-381..." /></FormField></WorkflowDialog>
    {preview && <WorkflowDialog open onOpenChange={(open) => !open && setPreview(null)} title={`${preview.time} · ${preview.app}`} description="Evidence preview đã làm mờ nội dung nhạy cảm." footer={<><button className="secondary-button" onClick={() => { const key = `${selected.name}-${preview.time}`; setDeletedEvents((current) => [...current,key]); record("Evidence deleted", key); setPreview(null); toast.success("Evidence đã xóa theo chính sách."); }}><Trash2 size={14} /> Xóa</button><button className="primary-button" onClick={() => { const key = `${selected.name}-${preview.time}`; setValidEvents((current) => [...new Set([...current,key])]); record("Evidence marked valid", key); setPreview(null); toast.success("Evidence đã được human reviewer xác nhận."); }}><Check size={14} /> Mark valid</button></>}><div className="evidence-preview"><div className="privacy-blur"><Monitor size={34} /><span>Nội dung đã được làm mờ</span></div><div><span>AI classification</span><strong>{preview.detail}</strong><span>Confidence</span><strong>{preview.confidence}%</strong><span>Linked report item</span><strong>{preview.task}</strong></div></div></WorkflowDialog>}
  </div>;
}

function EmployeeWfhIntelligence() {
  const [section, setSection] = useState<"overview" | "session" | "privacy">("overview");
  const employeeNav = [
    { id: "overview" as const, label: "Tổng quan", icon: LayoutDashboard },
    { id: "session" as const, label: "Phiên của tôi", icon: Monitor },
    { id: "privacy" as const, label: "Quyền riêng tư", icon: LockKeyhole },
  ];

  return <div className="ai-product-shell wfh-product employee-wfh-intelligence">
    <header className="ai-product-header"><div className="ai-product-identity"><span className="ai-product-symbol"><ShieldCheck size={20} /></span><div><span>OHRIISE · PERSONAL WFH</span><h1>WFH Intelligence</h1><p>Không gian WFH cá nhân · dữ liệu chỉ trong phạm vi của bạn</p></div></div><div className="ai-product-actions"><StatusPill tone="success"><LockKeyhole size={14} /> Self scope</StatusPill></div></header>
    <nav className="ai-internal-nav" aria-label="Điều hướng WFH Intelligence cá nhân">{employeeNav.map((item) => { const Icon = item.icon; return <button className={section === item.id ? "is-active" : ""} key={item.id} onClick={() => setSection(item.id)}><Icon size={15} /><span>{item.label}</span></button>; })}</nav>
    {section === "overview" && <section className="ai-app-overview"><div className="ai-overview-copy"><span className="eyebrow">PHIÊN WFH CỦA BẠN</span><h2>Minh bạch tín hiệu công việc, quyền riêng tư luôn hiển thị.</h2><p>AI chỉ hỗ trợ phân loại tín hiệu trong phiên WFH đã được duyệt. Bạn có thể xem trạng thái phiên, phạm vi dữ liệu và thời hạn lưu giữ của chính mình.</p><div className="ai-overview-actions"><button className="primary-button" onClick={() => setSection("session")}>Xem phiên gần nhất</button><button className="secondary-button" onClick={() => setSection("privacy")}>Chính sách riêng tư</button></div><div className="ai-activity-strip"><div><strong>Đã hoàn tất</strong><span>Phiên 02/10/2026</span></div><div><strong>6</strong><span>Tín hiệu công việc</span></div><div><strong>30 ngày</strong><span>Thời hạn lưu giữ</span></div></div></div><div className="ai-landing-art"><Image src="/assets/ohriise/06_wfh-monitoring_ai-activity-review_remote-work.png" alt="Minh họa WFH Intelligence cá nhân" width={430} height={323} priority /></div></section>}
    {section === "session" && <section className="employee-session-summary"><header><div><span className="eyebrow">02/10/2026 · WFH CẢ NGÀY</span><h2>Phiên làm việc của Nguyễn Thu Hà</h2><p>08:31–17:46 · Daily Report đã gửi 17:42</p></div><StatusPill tone="success"><Check size={13} /> Đã hoàn tất</StatusPill></header><div className="employee-signal-timeline">{[["08:31","Bắt đầu phiên","Consent active · HCM-Q1"],["09:18","Figma","Employee flow · tín hiệu công việc"],["11:06","Google Meet","Design review · lịch nội bộ"],["14:22","Notion","Cập nhật component documentation"],["17:42","Daily Report","3/3 đầu việc đã báo cáo"],["17:46","Kết thúc phiên","Không có mục cần làm rõ"]].map((event, index) => <div key={event[0]}><time>{event[0]}</time><i className={index === 5 ? "done" : ""} /><span><strong>{event[1]}</strong><small>{event[2]}</small></span></div>)}</div><div className="employee-session-note"><ShieldCheck size={17} /><p>Đây là bản tóm tắt của chính bạn. Ảnh bằng chứng gốc và công cụ review nâng cao chỉ dành cho reviewer được phân quyền.</p></div></section>}
    {section === "privacy" && <section className="privacy-command-center"><header><ShieldCheck size={24} /><div><span className="eyebrow">PRIVACY & CONSENT</span><h2>Dữ liệu WFH của bạn</h2><p>Chính sách áp dụng rõ ràng trước khi phiên bắt đầu.</p></div></header><div className="privacy-policy-grid"><div><UserCheck size={18} /><span><strong>Consent</strong><small>Xác nhận trước mỗi phiên được duyệt</small></span><StatusPill tone="success">Active</StatusPill></div><div><Monitor size={18} /><span><strong>Dữ liệu được ghi nhận</strong><small>Ứng dụng công việc, timestamp, ảnh đã blur</small></span><b>Giới hạn</b></div><div><Clock3 size={18} /><span><strong>Retention</strong><small>Tự động xóa bằng chứng</small></span><b>30 ngày</b></div><div><Eye size={18} /><span><strong>Người có thể truy cập</strong><small>Team Lead được phân công hoặc HR reviewer</small></span><b>Có audit</b></div></div><div className="employee-session-note"><LockKeyhole size={17} /><p>Không ghi phím, không đọc nội dung cá nhân và không dùng confidence thấp để tự động kết luận hành vi.</p></div></section>}
  </div>;
}
